---
# Quickly remove a user account from an instance
- hosts: all
  become: yes
  become_user: root
  vars:
    the_user: "USERTOREMOVE"
    the_key: "ssh-rsa PUBKEY"
  tasks:
    - name: Remove SSH
      authorized_key:
        user: ubuntu or root or admin
        key: "{{ the_key }}"
        state: absent

    - shell: pkill -u {{ the_user }} || true
    - pause: seconds=1
    - shell: pkill -9 -u {{ the_user }} || true

    - name: Remove user
      user:
        name: "{{ the_user }}"
        state: absent

    # Use this task to test everything during prep of final run
    - name: Test task
      stat:
        path: /home/{{ the_user }}
      register: st
    - debug: msg="{{ st.stat.exists }}"
